INSERT INTO INGREDIENTS ( ING_NAME, ING_CODE) VALUES ('Mehl', AA);
INSERT INTO INGREDIENTS ( ING_NAME, ING_CODE) VALUES ('Milch', AB);
INSERT INTO INGREDIENTS ( ING_NAME, ING_CODE) VALUES ('Eier', AC);
INSERT INTO INGREDIENTS ( ING_NAME, ING_CODE) VALUES ('Zucker', AD);
INSERT INTO INGREDIENTS ( ING_NAME, ING_CODE) VALUES ('Thunfisch', AE);